### ISSUE TITLE
Add helper functions to format input

### ISSUE THREAD

**Issue by benma** [aaron-em/rcirc-styles.el#4]
Thanks for this package.

Would it be hard to add some helper functions to insert escape codes to add colors and formatting to the text I input? I.e. bold and red.

Maybe an interactive function that does (read-from-minibuffer) with all the supported colors from the color vector, plus bold/underlined/... as completion options, which inserts the corresponding escape code?

**Comment by aaron-em** [comment]
Seems like it should be pretty easy, although perhaps best implemented as a pair of functions e.g. `rcirc-styles-insert-color` and `rcirc-styles-insert-attribute` since completion for all the possible (color, style) combinations would probably get hairy fast. Those commands could then be bound to e.g. C-c C-s C-c and C-c C-s C-a for ease of access.

I'm not sure when I'll get a chance to implement these functions; it may not be until this weekend. In the interim, style and color codes can be inserted literally via C-q. For example:

`C-q C-c 2,0` inserts the color code for blue text on a white background.
`C-q C-b` inserts the attribute code to toggle bold text.
`C-q C-o` inserts the attribute code to disable all preceding specifications.

And so forth. This is actually how I've been doing it up to now; since I don't actually use color codes very often, but mainly just want them to be interpreted properly when others do, I haven't heretofore worried about improving the insertion interface. Thanks for giving me the impetus to do so!

**Comment by aaron-em** [comment]
This is underway in [feature/#4](https://github.com/aaron-em/rcirc-styles.el/tree/feature/%234). It's not yet covered by unit tests, but if you want to try it out before it lands on MELPA, feel free to clone the repo and check out the branch.

**Comment by aaron-em** [comment]
So it looks like rcirc-mode-map does actually include a binding for `C-c C-s` by default, which means I'm overriding it and didn't want to. I'm going to chop the binding to rcirc-mode-map out of this and #5 for the moment, and do a proper job of customization support in a separate issue.

In the meantime, you can manually hang `rcirc-styles-map` off whatever prefix you like:

`(define-key rcirc-mode-map
    (kbd "WHATEVER-PREFIX") rcirc-styles-map)`

**Comment by aaron-em** [comment]
@benma Can I get you to look over #7 and give me any feedback you have on how I'm thinking of implementing that? You're the only rcirc-styles user I actually know I have at this point, so I'd quite like your opinion of the direction I have in mind for it. Thanks!

**Comment by benma** [comment]
Sorry for the late response. You seem to be putting a lot of effort into it, thanks for that! 

I am currently traveling and unable to test your new features yet, but I will do so once I am back. Thanks for asking for my feedback, but I trust you will create an adequate solution :)

**Comment by aaron-em** [comment]
I appreciate the vote of confidence!

**Comment by aaron-em** [comment]
@benma Version 1.3 just landed, so MELPA should be picking it up pretty soon - if it goes the way 1.2 did, stable will get it first, followed by unstable. (Both will get the same code, though.) So when you get done traveling, you should be able just to update the package, and then try out the new features. Let me know how it goes!

**Comment by benma** [comment]
@aaron-em Thanks, good job! It works.

Maybe one little nit-pick: if you toggle the preview, it only shows the preview of the already written stuff. Even cooler would be if when you use `rcirc-styles-insert-attribute` after toggling preview and keep writing, with the preview applied also to that. Not sure if this is even possible.

But this is certainly good enough for now. Thanks again!

**Comment by benma** [comment]
@ChangeTip, send $2 to @aaron-em

**Comment by changetip** [comment]
Hi @aaron-em, @benma sent you a tip worth 4,478 bits ($2.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/934005)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by aaron-em** [comment]
No problem! Glad you're finding it useful.

In re: inserting during preview (aka direct editing of styled text), that is actually something I want to look at, but it's going to be a while before that happens, and I'm not sure it's even possible, either -- well, say rather that I'm not sure it's possible without a lot more effort than I think it's worth, since it seems to imply a lot of the same complexity that word processors have to deal with. On the other hand, I seem dimly to remember that Emacs has some user-exposed functionality around applying arbitrary properties to text, and it might actually be easier to leverage that for editing, and then translate the property spans to style codes before sending text to the IRC server.

Either way, it'll be a while, but it is on the radar. If you come up with a brilliant solution in the meantime, of course, you're more than welcome to put it in a pull request!

**Comment by aaron-em** [comment]
(Also, while I appreciate the thought behind your tip, I'm unable to collect it, and I don't really look for remuneration in my open source work in any case. If you ever happen to find yourself in Baltimore, though, feel free to buy me a beer! :smile:)

**Comment by benma** [comment]
That's cool :) Why are you unable to collect it, I wonder?

Another thing: I would not mind merging foreground and background colors and attributes in one big autocompletion command.

Right now, normally I only want a color and/or an attribute, so splitting the color in two steps, fg/bg, is a bit distracting. Same for choosing between the two commands. If I have completion, completing for `red` and `red (bg)` and `underline` all works well, I think.

**Comment by aaron-em** [comment]
That sounds like a great idea. I'll add it to the roadmap for 1.4.
